controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

checkout:
    path: /checkout
    controller: App\Controller\CheckoutController::checkout
    methods: [GET, POST]